name: scalable-pipeline
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pandas=1.5.2
  - jupyter=1.0.0
  - jupyterlab=3.5.2
  - mamba=1.1.0
  - numpy=1.24.1
  - dvc=2.38.1
  - scikit-learn=1.1.3
  - pytest=7.2.0
  - pip=22.3.1
  - pip:
      - uvicorn==0.20.0
      - fastapi==0.89.0
      - httpx==0.23.3